//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestInicioSesion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedor()
        {
            this.Producto_Proveedor = new HashSet<Producto_Proveedor>();
        }
    
        public int codigo_proveedor { get; set; }
        public string rut_proveedor { get; set; }
        public string nombre_proveedor { get; set; }
        public string apellido_paterno_proveedor { get; set; }
        public string apellido_materno_proveedor { get; set; }
        public int codigo_tipoProducto { get; set; }
        public string direccion_proveedor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producto_Proveedor> Producto_Proveedor { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
