//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_Express_visual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Mesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Detalle_Mesa()
        {
            this.BoletaComanda = new HashSet<BoletaComanda>();
        }
    
        public int codigo_menu { get; set; }
        public int codigo_comanda { get; set; }
        public System.DateTime fecha_comanda { get; set; }
        public Nullable<int> precio_total { get; set; }
        public Nullable<int> cant_Menu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoletaComanda> BoletaComanda { get; set; }
        public virtual ComandaMesa ComandaMesa { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
