//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_Express_visual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Mesa_Pedido
    {
        public int idMesa { get; set; }
        public int codigo_comanda { get; set; }
        public int precio_total { get; set; }
        public Nullable<int> menu1 { get; set; }
        public Nullable<int> menu2 { get; set; }
        public Nullable<int> menu3 { get; set; }
        public Nullable<int> menu4 { get; set; }
        public Nullable<int> menu5 { get; set; }
        public Nullable<int> menu6 { get; set; }
        public Nullable<int> menu7 { get; set; }
        public Nullable<int> menu8 { get; set; }
        public Nullable<int> menu9 { get; set; }
        public Nullable<int> menu10 { get; set; }
        public Nullable<int> menu11 { get; set; }
        public Nullable<int> menu12 { get; set; }
        public Nullable<int> menu13 { get; set; }
        public Nullable<int> menu14 { get; set; }
        public Nullable<int> menu15 { get; set; }
        public Nullable<int> menu16 { get; set; }
        public Nullable<int> menu17 { get; set; }
        public Nullable<int> menu18 { get; set; }
        public Nullable<int> menu19 { get; set; }
        public Nullable<int> menu20 { get; set; }
        public Nullable<int> menu21 { get; set; }
        public Nullable<int> menu22 { get; set; }
        public Nullable<int> menu23 { get; set; }
        public Nullable<int> menu24 { get; set; }
        public Nullable<int> menu25 { get; set; }
        public Nullable<int> menu26 { get; set; }
        public Nullable<int> menu27 { get; set; }
        public Nullable<int> menu28 { get; set; }
        public Nullable<int> menu29 { get; set; }
        public Nullable<int> menu30 { get; set; }
    
        public virtual ComandaMesa ComandaMesa { get; set; }
        public virtual Mesa Mesa { get; set; }
    }
}
