//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_Express_visual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Mesa_Pedido
    {
        public int idMesa { get; set; }
        public int codigo_comanda { get; set; }
        public int precio_total { get; set; }
        public string menu1 { get; set; }
        public Nullable<int> cantidad_m1 { get; set; }
        public string menu2 { get; set; }
        public Nullable<int> cantidad_m2 { get; set; }
        public string menu3 { get; set; }
        public Nullable<int> cantidad_m3 { get; set; }
        public string menu4 { get; set; }
        public Nullable<int> cantidad_m4 { get; set; }
        public string menu5 { get; set; }
        public Nullable<int> cantidad_m5 { get; set; }
        public string menu6 { get; set; }
        public Nullable<int> cantidad_m6 { get; set; }
        public string menu7 { get; set; }
        public Nullable<int> cantidad_m7 { get; set; }
        public string menu8 { get; set; }
        public Nullable<int> cantidad_m8 { get; set; }
        public string menu9 { get; set; }
        public Nullable<int> cantidad_m9 { get; set; }
        public string menu10 { get; set; }
        public Nullable<int> cantidad_m10 { get; set; }
        public string menu11 { get; set; }
        public Nullable<int> cantidad_m11 { get; set; }
        public string menu12 { get; set; }
        public Nullable<int> cantidad_m12 { get; set; }
        public string menu13 { get; set; }
        public Nullable<int> cantidad_m13 { get; set; }
        public string menu14 { get; set; }
        public Nullable<int> cantidad_m14 { get; set; }
        public string menu15 { get; set; }
        public Nullable<int> cantidad_m15 { get; set; }
        public string menu16 { get; set; }
        public Nullable<int> cantidad_m16 { get; set; }
        public string menu17 { get; set; }
        public Nullable<int> cantidad_m17 { get; set; }
        public string menu18 { get; set; }
        public Nullable<int> cantidad_m18 { get; set; }
        public string menu19 { get; set; }
        public Nullable<int> cantidad_m19 { get; set; }
        public string menu20 { get; set; }
        public Nullable<int> cantidad_m20 { get; set; }
        public string menu21 { get; set; }
        public Nullable<int> cantidad_m21 { get; set; }
        public string menu22 { get; set; }
        public Nullable<int> cantidad_m22 { get; set; }
        public string menu23 { get; set; }
        public Nullable<int> cantidad_m23 { get; set; }
        public string menu24 { get; set; }
        public Nullable<int> cantidad_m24 { get; set; }
        public string menu25 { get; set; }
        public Nullable<int> cantidad_m25 { get; set; }
        public string menu26 { get; set; }
        public Nullable<int> cantidad_m26 { get; set; }
        public string menu27 { get; set; }
        public Nullable<int> cantidad_m27 { get; set; }
        public string menu28 { get; set; }
        public Nullable<int> cantidad_m28 { get; set; }
        public string menu29 { get; set; }
        public Nullable<int> cantidad_m29 { get; set; }
        public string menu30 { get; set; }
        public Nullable<int> cantidad_m30 { get; set; }
    
        public virtual Mesa Mesa { get; set; }
    }
}
