//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pizza_Express_visual.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportesVentas
    {
        public int idReportesVentas { get; set; }
        public int codigo_comanda { get; set; }
        public int codigo_menu { get; set; }
        public string nombre_menu { get; set; }
        public int precio_menu { get; set; }
        public int cantidad { get; set; }
    
        public virtual ComandaMesa ComandaMesa { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
