//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestSprint2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto_Proveedor
    {
        public int codigo_producto { get; set; }
        public int codigo_proveedor { get; set; }
        public System.DateTime fecha_ingreso_producto { get; set; }
        public int cantidad_producto { get; set; }
    
        public virtual Producto Producto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
